# Generated by Django 4.2.7 on 2024-07-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('index_number', models.CharField(max_length=20)),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
