# Generated by Django 4.2.7 on 2024-07-19 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='index_number',
            new_name='index_no',
        ),
    ]
